In [1]:
import pandas as pd
import plotly.express as px

# Downloading the Module

In [2]:
import requests
from requests.structures import CaseInsensitiveDict
import time
import numpy as np
from tqdm.auto import tqdm

headers = CaseInsensitiveDict()
headers["User-Agent"] = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
headers["Accept"] = "*/*"
headers["Accept-Language"] = "en-US,en;q=0.5"
headers["Accept-Encoding"] = "gzip, deflate, br"
headers["X-XSRF-Token"] = "mmMjB3kLenIMupo3IThoaeRRW0UV3o31qVb8sixhbVU6MTY1Mzk3MTc1MTY3MTk4MQ"
headers["Alt-Used"] = "code.earthengine.google.com"
headers["Connection"] = "keep-alive"
headers["Referer"] = "https://code.earthengine.google.com/"
headers["Cookie"] = "1P_JAR=2022-05-31-01; NID=511=XAJXIN11-guhKiTPRsJhKrEV1D5AJ3iY_s-7PyjV4rvl7UwpMwTtrrLewIkwHdVhi1l--OQg_2Sl2r1D5r3n9MC6uvxE7hQstocfmElAsbZg47zX_oOEk5Ozao4_NWBs3myHmQef1AJ8BlgE4lrZKLqLp_BabJwLGOFeFNrwmUOBkagI74gmec41C6jzrL734wQ-Rp5YTFdzWu7buujETbx49b6NB7UpXdR3G1TGzsVYT3Plad-1V2vve5yEvSihphEALkycWsptVg; ANID=AHWqTUmJdq0vDL4Z7uLTot5-L3aWh55_ZGEN6tOheC_Bg_DpklE2ztrU4YA3U2Z4; SID=Jwh6GiRL_nGjImygRU6UmRILgXjZhkKtBDcAFvSEIgzqMUjQpPpMH9MecOA6C6VnZnwh6Q.; __Secure-1PSID=Jwh6GiRL_nGjImygRU6UmRILgXjZhkKtBDcAFvSEIgzqMUjQH7YB7V_qYFOuNQwkaiuvxw.; __Secure-3PSID=Jwh6GiRL_nGjImygRU6UmRILgXjZhkKtBDcAFvSEIgzqMUjQyWR1MsGBd8goPhhO7UV5BQ.; HSID=AxdwUO3f0O_lCMRN-; SSID=AViyfMy4w2gjW28ep; APISID=RfCcb01m2oWmTnl-/AAxipeHixZG4V3Tmz; SAPISID=mhwK7VlBnufaU9_b/Abpt5kkMMbsD_dVnv; __Secure-1PAPISID=mhwK7VlBnufaU9_b/Abpt5kkMMbsD_dVnv; __Secure-3PAPISID=mhwK7VlBnufaU9_b/Abpt5kkMMbsD_dVnv; SIDCC=AJi4QfHYxOjUdUOtsG-eTYvPdTBZNBG-xT69pTEAtXoPtt4u32MzxyZUGuKKEI0sGzzTkQWRVgY; __Secure-3PSIDCC=AJi4QfEZ-vkhCrFKAaDlSoeV2QJh3n9XU72Ef747wdrBVXAwKzR1RXZ5XfJeLo0lmPHBeJiFCxIb; SEARCH_SAMESITE=CgQIxZUB; __Secure-1PSIDCC=AJi4QfGp803AGvRQqa3rQH5QdFoq90ODVDoX5gTx7E6z6660qPi57cp26mk1704a9vDvBizYWFo; _ga=GA1.3.1593770581.1627864665; _ga=GA1.1.1593770581.1627864665; AEC=AakniGNv4phNgGeMr4s682zSpI7SsDWkUSa5Z68Z4HYFfpxyRus-vIr8rlg; SACSID=~AJKiYcEgQMYj7_q5eEeXa-lpsXUg3YRGNHFm39cAj2NnW9U9B51jG3uF-Nk4wgcaWqDwHFh7rfkHkiDDB0cz2rK6YFBp4ZgZRcUT3bTivVtzo7wZJCmAMWgVB8H-hTxPACPNGN3kQgFKYXDgWzg5FlEBq-Xl577tyq-0JbM4hf15iN8RgBcMVVu0iKM1ZOR0E5FqOOj8EiYjQztOJauWTbYycVRWm9u84SQ-FJrTH9HDkQYtDQfcggdMguoLuEdJJE8j2NXdiCVyYQpipOpIO1rdL4CW-mEyipIm8wMR_sOiABTh8OgjKS9-NqNX_WoCz29SeyNKaClCqTZT9-4HMUnHwyI0U1I34Sj0MlGc5DRYhXMoIzWnOHGlu4G-tNWJXE1o8wcm7zyILPJ1jJoKoID8mYseOrCqRA; _gid=GA1.3.2008653051.1653944495; _gat=1"
headers["Sec-Fetch-Dest"] = "empty"
headers["Sec-Fetch-Mode"] = "cors"
headers["Sec-Fetch-Site"] = "same-origin"
headers["TE"] = "trailers"

## Minified

In [49]:
url = "https://code.earthengine.google.com/repo/file/load?repo=users%2Faazuspan%2Fminify_test&path=msslib_mini"


elapsed = []
total = []

for i in tqdm(range(100)):
    start = time.perf_counter()
    resp = requests.get(url, headers=headers)
    total_time = time.perf_counter() - start

    elapsed.append(resp.elapsed.total_seconds())
    total.append(total_time)
    
    time.sleep(0.25)

df_mini = pd.DataFrame({'server_s': elapsed, 'total_s': total})
df_mini["download_s"] = df_mini["total_s"] - df_mini["server_s"]
df_mini["version"] = "minified"

  0%|          | 0/100 [00:00<?, ?it/s]

## Original

In [51]:
url = "https://code.earthengine.google.com/repo/file/load?repo=users%2Faazuspan%2Fminify_test&path=msslib_original"

elapsed = []
total = []

for i in tqdm(range(100)):
    start = time.perf_counter()
    resp = requests.get(url, headers=headers)
    total_time = time.perf_counter() - start

    elapsed.append(resp.elapsed.total_seconds())
    total.append(total_time)
    
    time.sleep(0.25)

df_original = pd.DataFrame({'server_s': elapsed, 'total_s': total})
df_original["download_s"] = df_original["total_s"] - df_original["server_s"]
df_original["version"] = "original"

  0%|          | 0/100 [00:00<?, ?it/s]

## Merging Data

In [69]:
(718 - 686) / 718

0.04456824512534819

In [52]:
df = pd.concat([df_mini, df_original])

# df = pd.read_csv("module_download_times.csv")

In [53]:
df["percent_download"] = (df["download_s"] / df["total_s"]) * 100

df.groupby("version").mean()

          server_s   total_s  download_s  percent_download
version
minified  0.680724  0.685963    0.005239          0.804755
original  0.673224  0.717678    0.044453          6.289971

In [54]:
df.to_csv("module_download_times.csv", index=False)

In [106]:
fig = px.scatter(
    df, x="download_s", y="server_s", color="version", 
    template="plotly_white",
    labels={"server_s": "Server Time (sec)", "download_s": "Download Time (sec)"})

fig.update_layout(
    legend=dict(
        yanchor="top",
        y=0.99,
        xanchor="left",
        x=0.8,
        bordercolor="black",
        borderwidth=1
        # bgcolor="rgba(255, 255, 255, 0)",
    ),
    margin=dict(l=20, r=20, t=20, b=20),
    legend_title_text="", font_size=18
)
# fig.update_xaxes(dtick=0.1, range=[0, 0.7])
fig.update_traces(marker=dict(size=12, line=dict(width=1, color="black")))
fig

In [107]:
fig.write_html("../assets/minified_download_server_time.html")

In [56]:
fig.write_image("../assets/minified_server_download_time.png")

In [104]:
fig = px.box(
    df, x="total_s", color="version", 
    labels={"total_s": "Total Request Time (sec)", "version": "Version"}, 
    width=800, height=300, template="plotly_white")

fig.update_layout(legend=dict(
    yanchor="top",
    y=0.99,
    xanchor="left",
    x=0.8,
    bgcolor="rgba(255, 255, 255, 0)",
), 
margin=dict(l=20, r=20, t=20, b=20),
legend_title_text="", font_size=18)

fig

In [58]:
fig.write_image("../assets/minified_total_time.png")

In [105]:
fig.write_html("../assets/minified_total_time.html")

In [70]:
df

    server_s   total_s  download_s   version  percent_download
0   0.710344  0.714446    0.004102  minified          0.574111
1   0.560666  0.563833    0.003167  minified          0.561758
2   0.770716  0.777966    0.007250  minified          0.931942
3   0.558427  0.562642    0.004215  minified          0.749097
4   0.561840  0.565275    0.003435  minified          0.607715
..       ...       ...         ...       ...               ...
95  0.569265  0.609455    0.040190  original          6.594401
96  0.565303  0.621331    0.056028  original          9.017423
97  0.637597  0.688853    0.051256  original          7.440822
98  0.551610  0.604462    0.052852  original          8.743589
99  0.778411  0.817746    0.039335  original          4.810191

[200 rows x 5 columns]

In [97]:
df_bar = df.groupby("version").mean().reset_index()[["version", "server_s", "download_s"]]
df_bar = df_bar.melt(id_vars=["version"])

In [103]:
fig = px.bar(
    df_bar, x="version", y="value", color="variable", 
    barmode="stack", template="plotly_white",
    labels={"value": "Time (sec)"},
    color_discrete_sequence=["#1f77b4", "#ff7f0e", "#2ca02c"]
)

fig.update_layout(legend=dict(
    yanchor="top",
    y=0.99,
    xanchor="left",
    x=0.8,
    bgcolor="rgba(255, 255, 255, 0)",
), 
margin=dict(l=20, r=20, t=20, b=20),
legend_title_text="", font_size=18)

fig